# docker-compose.yml

version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-user-loopback
    environment:
      MYSQL_DATABASE: user_loopback
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
      - user_loopback_test_data:/var/lib/mysql

volumes:
  user_loopback_test_data:
